## SVD

In [2]:
## Import Library
import numpy as np

In [5]:
# define a matrix
A = np.array([
    [1, 1, 1, 0, 0], 
    [3, 3, 3, 0, 0],
    [4, 4, 4, 0, 0],
    [5, 5, 5, 0, 0],
    [0, 2, 0, 4, 4],
    [0, 0, 0, 5, 5],
    [0, 1, 0, 2, 2]])
print(A)

[[1 1 1 0 0]
 [3 3 3 0 0]
 [4 4 4 0 0]
 [5 5 5 0 0]
 [0 2 0 4 4]
 [0 0 0 5 5]
 [0 1 0 2 2]]


In [6]:
# Compute the factor by Singular Value 
# Decomposition
U, S, Vt = np.linalg.svd(A, full_matrices=False)

In [7]:
# Print the result
print("\nFactor of the given array by Singular Value Decomposition:")
print("\nU =", U, "\n\nS =", S, "\n\nV=", Vt)


Factor of the given array by Singular Value Decomposition:

U = [[-1.37599126e-01 -2.36114514e-02 -1.08084718e-02  5.60112034e-01
  -3.75734575e-01]
 [-4.12797378e-01 -7.08343543e-02 -3.24254153e-02  2.06393278e-01
   7.55974371e-01]
 [-5.50396503e-01 -9.44458057e-02 -4.32338870e-02 -7.24808963e-01
  -1.84603760e-01]
 [-6.87995629e-01 -1.18057257e-01 -5.40423588e-02  3.43988797e-01
  -2.30754700e-01]
 [-1.52775087e-01  5.91100963e-01  6.53650843e-01  2.58497890e-16
   2.00000000e-01]
 [-7.22165140e-02  7.31311857e-01 -6.78209218e-01  0.00000000e+00
   0.00000000e+00]
 [-7.63875433e-02  2.95550482e-01  3.26825421e-01  1.29248945e-16
  -4.00000000e-01]] 

S = [1.24810147e+01 9.50861406e+00 1.34555971e+00 3.04642685e-16
 0.00000000e+00] 

V= [[-5.62258405e-01 -5.92859901e-01 -5.62258405e-01 -9.01335372e-02
  -9.01335372e-02]
 [-1.26641382e-01  2.87705846e-02 -1.26641382e-01  6.95376220e-01
   6.95376220e-01]
 [-4.09667482e-01  8.04791520e-01 -4.09667482e-01 -9.12571001e-02
  -9.12571001e

In [26]:
# Orthogonal
print ('Norm of col1 of U:', np.linalg.norm(U[:,0]))
print ('Norm of col2 of U:', np.linalg.norm(U[:,1]))
print ('Norm of col1 of Vt:', np.linalg.norm(V[:,0]))
print ('Norm of col2 of Vt:', np.linalg.norm(V[:,1]))

print ("U.U*", np.dot(U, np.transpose(U)))
print ("V.V*", np.dot(Vt, np.transpose(Vt)))

Norm of col1 of U: 1.0
Norm of col2 of U: 1.0
Norm of col1 of Vt: 0.9545214
Norm of col2 of Vt: 0.8944272
U.U* [[ 0.9891963   0.05606773 -0.07972414  0.03446018]
 [ 0.05606773  0.7090282   0.41374046 -0.17883636]
 [-0.07972414  0.41374046  0.41169152  0.25429216]
 [ 0.03446018 -0.17883636  0.25429216  0.8900841 ]]
V.V* [[ 1.0000001e+00 -9.0690691e-09  1.7486492e-08]
 [-9.0690691e-09  9.9999994e-01 -1.4670803e-08]
 [ 1.7486492e-08 -1.4670803e-08  1.0000000e+00]]
