## SVD

In [1]:
## Import Library
import numpy as np

In [14]:
# define a matrix
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]],dtype=np.float32)
print(A)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [16]:
# Compute the factor by Singular Value 
# Decomposition
U, S, Vt = np.linalg.svd(A, full_matrices=False)

In [17]:
# Print the result
print("\nFactor of the given array by Singular Value Decomposition:")
print("\nU =", U, "\n\nS =", S, "\n\nV=", Vt)


Factor of the given array  by Singular Value Decomposition:

U = [[-0.14087668 -0.82471436  0.5377697 ]
 [-0.3439463  -0.42626393 -0.6395531 ]
 [-0.5470159  -0.02781353 -0.33420283]
 [-0.75008553  0.37063688  0.43598625]] 

S = [2.5462408e+01 1.2906617e+00 2.3117338e-15] 

V= [[-0.5045332  -0.5745157  -0.6444983 ]
 [ 0.7607757   0.05714052 -0.6464946 ]
 [-0.4082483   0.8164966  -0.4082483 ]]


In [26]:
# Orthogonal
print ('Norm of col1 of U:', np.linalg.norm(U[:,0]))
print ('Norm of col2 of U:', np.linalg.norm(U[:,1]))
print ('Norm of col1 of Vt:', np.linalg.norm(V[:,0]))
print ('Norm of col2 of Vt:', np.linalg.norm(V[:,1]))

print ("U.U*", np.dot(U, np.transpose(U)))
print ("V.V*", np.dot(Vt, np.transpose(Vt)))

Norm of col1 of U: 1.0
Norm of col2 of U: 1.0
Norm of col1 of Vt: 0.9545214
Norm of col2 of Vt: 0.8944272
U.U* [[ 0.9891963   0.05606773 -0.07972414  0.03446018]
 [ 0.05606773  0.7090282   0.41374046 -0.17883636]
 [-0.07972414  0.41374046  0.41169152  0.25429216]
 [ 0.03446018 -0.17883636  0.25429216  0.8900841 ]]
V.V* [[ 1.0000001e+00 -9.0690691e-09  1.7486492e-08]
 [-9.0690691e-09  9.9999994e-01 -1.4670803e-08]
 [ 1.7486492e-08 -1.4670803e-08  1.0000000e+00]]
